[tool.poetry]
name = "mergics"
version = "0.1.0"
description = "Merge multiple ICS streams"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-Clause"

[tool.poetry.dependencies]
python = "^3.10"
ndh = "^6.5.3"
icalendar = "^5.0.11"
requests = "^2.31.0"
gunicorn = "^21.2.0"
yeouia = "^4.0.0"
redis = "^5.0.1"
ipython = "^8.18.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.11.0"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
gunicorn = "^21.2.0"
psycopg2 = "^2.9.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
