[tool.poetry]
name = "mergics"
version = "0.1.0"
description = "Merge multiple ICS streams"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-Clause"

[tool.poetry.dependencies]
python = "^3.10"
ndh = "^6.2.0"
icalendar = "^5.0.7"
requests = "^2.31.0"
gunicorn = "^20.0.4"
yeouia = "^4.0.0"
redis = "^4.6.0"
ipython = "^8"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
gunicorn = "^20.1.0"
psycopg2 = "^2.9.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
