# Generated by Django 4.2.7 on 2023-11-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mergics", "0002_alter_icsinput_id_alter_icsoutput_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="icsoutput",
            name="filtre",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
