# Generated by Django 4.2.7 on 2024-01-08 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mergics", "0003_icsoutput_filtre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="icsoutput",
            old_name="filtre",
            new_name="filter",
        ),
    ]
