name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          tags: nim65s/mergics
          load: true
      - name: Run django tests
        run: |
          docker network create web
          echo SECRET_KEY=secret_key >> .env
          echo POSTGRES_PASSWORD=postgres_password >> .env
          docker-compose up --exit-code-from test test
